module.exports = {
  content: [
    "./src/**/*.{html,njk,js}", 
    "./.eleventy.js",
    "./helpers/**/*.js"
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        'display': ['"Playfair Display"', 'serif'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
    require('@tailwindcss/aspect-ratio'),
  ],
  // Aggressive purging with safelist for dynamic classes
  safelist: [
    // Dynamic classes from templates
    'text-[6em]',
    'leading-[1.15em]',
    'text-[8px]',
    'text-[10px]',
    'w-[1200px]',
    'w-[55rem]',
    'w-[57.875rem]',
    'w-[64rem]',
    'w-[79.125rem]',
    'max-w-[400px]',
    'h-[64rem]',
    'top-[110px]',
    'pr-[30%]',
    'rounded-br-[50px]',
    'rounded-2xl',
    'rounded-t-2xl',
    'rounded-b-2xl',
    'rounded-l-2xl',
    'rounded-r-2xl',
    // Essential utility classes
    'bg-gray-50',
    'relative',
    'prose',
    'overflow-hidden',
    'mx-auto',
    'max-w-xl',
    'p-4',
    // Navigation classes
    'bg-white',
    'sticky',
    'w-full',
    'top-0',
    'z-40',
    // Hero classes
    'hero',
    'post',
    // Archive page classes (used in Alpine.js templates)
    'col-span-full',
    'grid',
    'grid-cols-2',
    'grid-cols-3',
    'grid-cols-6',
    'gap-4',
    'gap-8',
    'aspect-w-1',
    'aspect-h-1',
    'aspect-square',
    'h-88',
    'h-64',
    'h-56',
    'h-full',
    'rounded-t',
    'rounded-b',
    'rounded-l',
    'rounded-r',
    'bg-cover',
    'bg-center',
    'object-cover',
    'border',
    'border-gray-300',
    'bg-opacity-0',
    'text-white',
    'text-gray-900',
    'hover:opacity-70',
    'loading',
    'decoding',
    'lazy',
    'async',
    // Color filter classes for images
    'saturate-200',
    'hue-rotate-[30deg]',
    'hue-rotate-[45deg]',
    'hue-rotate-[60deg]',
    'hue-rotate-[90deg]',
    'hue-rotate-[180deg]',
    'hue-rotate-[240deg]',
    'hue-rotate-[270deg]',
    'hue-rotate-[300deg]',
    '-hue-rotate-[30deg]',
    // Responsive classes for hero and layout
    'sm:rounded-xl',
    'sm:rounded-l-2xl',
    'sm:rounded-r-2xl',
    'sm:rounded-tl-2xl',
    'sm:rounded-tr-none',
    'sm:rounded-bl-2xl',
    'sm:rounded-br-none',
    'sm:rounded-t-none',
    'sm:rounded-l-none',
    'sm:rounded-l',
    'sm:rounded-r',
    'md:rounded-l-2xl',
    'md:rounded-r-2xl',
    'md:rounded-tl-2xl',
    'md:rounded-tr-none',
    'md:rounded-bl-2xl',
    'md:rounded-br-none',
    'md:rounded-l-none',
    'md:rounded-r-none',
    'md:border-l-0',
    'sm:h-24',
    'sm:w-1/2',
    'sm:flex',
    'sm:flex-shrink-0',
    'sm:grid-cols-2',
    'sm:grid-cols-3',
    'sm:px-6',
    'sm:px-8',
    'sm:py-24',
    'sm:text-5xl',
    'md:text-4xl',
    'md:text-6xl',
    'md:text-center',
    'md:pr-16',
    'md:my-6',
    'md:px-10',
    'md:gap-y-16',
    'md:inline-block',
    'lg:text-5xl',
    'xl:text-5xl'
  ],

};
