AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.handler
      Runtime: nodejs20.x
      FunctionName: NJKPostLambdaGithubSAM
      Timeout: 15
      FunctionUrlConfig:  # Add this block for the Function URL
        AuthType: NONE    # Use NONE for public access or AWS_IAM for restricted access